### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by Mumfrey** [SpongePowered/SpongeHome#52]
Whilst discussing the staging site during SPAM yesterday I noticed some minor off-brand issues with the site which should be pretty simple to rectify but aren't really big enough problems to create an issue for each one. Listing here with check marks for ease of use:
- [x] Some components (notably the "get sponge" buttons, and some body text) use `#2c3e50` which is an off-brand colour which is basically a very dark navy blue, this should be replaced with 20% grey (`#333333`)
- [x] Some components (the "get sponge buttons") use `#1a242f` as a hover colour with `#161f29` border, this should again be a mid grey or an on-brand colour such as `#f8ce0f`
- [x] Some components (notably some titles, the word _SPONGE_ on the main landing page, and the hover colour for some items such as the links on the home page) use `#000000` which is off-brand and should also be a dark grey such as `#2b2b2b` to match the spongie mark
- [x] Hover colour for the _Interested in Sponsoring sponge?_ button uses off-brand `#cc8800`
- [x] The yellow "sun rays" image on the main splash is generally the wrong hue and doesn't match the brand yellow. The hue should be corrected to 49° to match the branding, or a different image should be used. [Here is a colour-corrected version](http://eq2.co.uk/sponge/sponsors-content.jpg).

Some other minor aesthetic/accessibility notes
- [x] Link text for github is "GitHub" on the strap links and "Code" on the pulldown
- [x] Link text for documentation is "Docs" on the strap links and "SpongeDocs" on the pulldown
- [x] Pulldown icons vary in size, some are 14x15, some are up to 19x15. This makes the alignment of the pulldown text very uneven.
- [x] No alt text for spongie logo on home page
- [x] No alt text for sponsor logos on sponsors page

Some aesthetic considerations which are merely my opinion:
- [x] The spongie mascot being animated feels tacky, I know it was part of the original home page but I would question its inclusion on the new page, which overall has a much more professional and less rushed appearance. The animated spongie undermines this somewhat in my opinion.
- [x] The social buttons look a bit untidy compared to their strap link counterparts. Maybe make them all grey to match?

**Comment by Zidane** [comment]
I agree on the animated spongie. It needs to go (sorry @jamierocks !)

**Comment by jamierocks** [comment]
Alright I'll add that to #54 ;)

**Comment by Tzky** [comment]
The only thing left now to get this resolved are the pulldown icons.
EDIT:
Should be resolved by giving the FA icons the `fa-fw` class for fixed width (bd2f430).

I'll close this issue for now as everything should be resolved.

**Comment by Mumfrey** [comment]
The following are still not resolved in the current build:
- [x] Some components (notably the "get sponge" buttons, and some body text) use #2c3e50 which is an off-brand colour which is basically a very dark navy blue, this should be replaced with 20% grey (#333333)

This applies to **all** of the body text on the `/sponsors` page as well as the "News" block text on the main page and the text "Get Sponge" on the main page.
- [x] Some components (notably some titles, the word SPONGE on the main landing page, and the hover colour for some items such as the links on the home page) use #000000 which is off-brand and should also be a dark grey such as #2b2b2b to match the spongie mark

This is still not resolved for the "Our sponsors" text on the home page.

**Comment by Tzky** [comment]
Fixed in 73776e1. If anything is still off, then bootstrap is messing with our colors.
